"""add user_id to companies

Revision ID: 23575c4c704c
Revises: 7a7d93dabce0
Create Date: 2026-07-03 11:35:04.804067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23575c4c704c'
down_revision: Union[str, Sequence[str], None] = '7a7d93dabce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'user_id')
    # ### end Alembic commands ###
