"""add user_id to companies

Revision ID: bf81b6779ed4
Revises: 23575c4c704c
Create Date: 2026-07-05 08:03:49.792772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf81b6779ed4'
down_revision: Union[str, Sequence[str], None] = '23575c4c704c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('company_code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'companies', ['company_code'])
    op.add_column('students', sa.Column('registration_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'students', ['registration_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'registration_number')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'company_code')
    op.drop_table('applications')
    op.drop_table('jobs')
    # ### end Alembic commands ###
